name: Math Utility Project using Maven and CI | © 2023 giáo.làng

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19 - Cài JDK lên server vừa mượn ở Mỹ
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven - Mượn maven của server Mỹ build app giùm
      run: mvn -B package --file pom.xml
    
    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
        name: moi-nha-tuyen-dung-xem-file-jar.zip #File .jar .war đc tạo ở Mỹ đc nén vào .zip để download 
        path: staging

   
